### ISSUE TITLE
请问rrt*的代码在计算搜索半径的时候nnodes需要加1吗？

### ISSUE THREAD

**Issue by guest-oo** [CHH3213/chhRobotics_CPP#10]
你的python代码中
nnode = len(self.node_list) + 1
        r = self.connect_circle_dist * math.sqrt((math.log(nnode) / nnode))

请问rrt*的代码在计算搜索半径的时候nnodes需要加1吗？

**Comment by guest-oo** [comment]
int nnode = node_list.size() + 1; 在cpp的这个位置的代码。

**Comment by CHH3213** [comment]
nnode = len(self.node_list) + 1 的目的是确保 nnode 的值不为零，以保证在算法的计算过程中不会出现除以零的错误。具体已在python 仓库issue中解释
