### ISSUE TITLE
运行速度

### ISSUE THREAD

**Issue by IamXulin** [CHH3213/chhRobotics_CPP#6]
按照道理c++应该比python快，我两种都试过之后，为啥c++比python慢这么多

**Comment by CHH3213** [comment]
> 按照道理c++应该比python快，我两种都试过之后，为啥c++比python慢这么多

你测试的是C++编译后，再运行打印出了相关代码段的运行时间吗？有差别可能是画图的原因，你可以试着看下算法核心部分运行的时间对比，另外要是运行时候的算法核心部分比python慢很多，那可能有变量类型使用不太恰当等原因，我没有测试过两者的时间耗时，因为写代码时候本身没有考虑算法运行耗时，主要还是在于算法的实现。
