### ISSUE TITLE
RRT代码疑惑

### ISSUE THREAD

**Issue by woyidingqu** [CHH3213/chhRobotics_CPP#9]
bool RRT::obstacleFree(Node* node)
      auto isSegmentIntersectingObstacle = [this](const Point& p1, const Point& p2)
中Point是在哪定义的，请问是在头文件中吗？

**Comment by CHH3213** [comment]
> bool RRT::obstacleFree(Node* node) auto isSegmentIntersectingObstacle = [this](const Point& p1, const Point& p2) 中Point是在哪定义的，请问是在头文件中吗？

https://github.com/CHH3213/chhRobotics_CPP/blob/3cc0432cb2485e2de25252361eead468b8f8351f/PathPlanning/utils/geometry_utils.h#L13

**Comment by woyidingqu** [comment]
谢谢你博主，祝你在新的一年万事如意，一帆风顺。
